---
title: "Fitting the COVID-19 curve"
author: "Artem Sokolov (Updated: `r Sys.Date()`)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library( tidyverse )
```

```{r echo=FALSE, warning=FALSE, out.width='100%'}
## Load the raw data
rawAll <- file.path("https://raw.githubusercontent.com/CSSEGISandData/COVID-19",
                  "master/csse_covid_19_data/csse_covid_19_time_series",
                  "time_series_19-covid-Confirmed.csv") %>%
  read_csv( col_types=cols() ) %>%
  rename( State = 1, Country = 2 )

## Identify the US slice
rawUS <- filter( rawAll, Country == "US" ) %>%
  select( -Lat, -Long, -Country ) %>%
  gather( Date, Confirmed, -State ) %>%
  na.omit() %>%
  mutate_at( "Date", lubridate::mdy )

## It appears that the most consistent tracking for the US began around 2/27
## Using the day before to remove the extra +/-1 in date arithmetic below
dStart <- lubridate::mdy("2/26/2020")

## Compute new confirmed cases for each day
US <- rawUS %>% group_by( Date ) %>%
  summarize_at( "Confirmed", sum ) %>%
  arrange( Date ) %>%
  mutate( New = c(0,diff(Confirmed)) ) %>%
  filter(Date > dStart)

## Fits a curve and generates predictions for k days forward
##   .df - data frame mapping Date -> Observation
##   obs - column in .df with observation values
##   f   - parametric distribution function
##   v0  - initial parameter estimates
##   k   - number of days to predict
fitCurve <- function( .df, obs, f, v0, k=5 ) {
  ## Compute day offset from start date
  .df <- .df %>% transmute( x = 1:n(), y = {{obs}} )
  
  ## Define the RMSE objective function
  fobj <- function(v) {(.df$y - f(.df$x, v))^2 %>% mean %>% sqrt}
  
  ## Optimize the objective function and compute predictions
  fit <- optim(v0, fobj)
  xp <- 1:(max(.df$x)+k)
  list( Pred = tibble( Date = dStart + lubridate::days(xp),
                       New = f(xp, fit$par) ),
        RMSE = fit$value )
}

## Will be fitting New Cases column in US data
fcurve <- partial( fitCurve, US, New )

## Define parametric distributions to fit to data
ldist <- list(
  "Gaussian Fit"   = function(x, p) {p[1] * dnorm(x, p[2], p[3])},
  "Log-normal Fit" = function(x, p) {p[1] * dlnorm(x-p[2], p[3], p[4])}
)

## Define starting parameters for each optimization problem
v0 <- list(
  c(max(US$New)*2, nrow(US), nrow(US)/2),
  c(1e5, 0, 5, 1)
)

## Fit the curves and combine predictions with observed data
fits <- map2( ldist, v0, fcurve )
P <- map( fits, pluck, "Pred" ) %>% c(list(Observed=US)) %>%
  imap( ~mutate(.x, Values=.y) ) %>% bind_rows %>%
  mutate( Hover = str_c("Date: ", Date, "<br>",
                        "New : ", as.integer(New), "<br>",
                        Values) )
  
## Plot results
etxt <- function(s, ...) {element_text( size = s, face = "bold", ... )}
pal <- c("Observed"="gray", "Gaussian Fit"="tomato", "Log-normal Fit"="steelblue")
gg <- 
  ggplot(mapping = aes(Date, New, fill=Values, color=Values,
                       group=Values, text=Hover)) +
  geom_bar( data=subset(P, Values=="Observed"), stat="identity" ) +
  geom_line( data=subset(P, Values!="Observed"), size=1.25 ) +
  scale_fill_manual(values=pal) + scale_color_manual(values=pal) +
  scale_x_date(date_breaks="2 days", date_labels="%b %d") +
  scale_y_continuous( name="New Cases in the U.S.", labels=scales::label_number_si() ) + 
  theme_bw() +
  theme( axis.text.y = etxt(12), axis.title = etxt(14),
         axis.text.x = etxt(12, angle=90, hjust=1, vjust=0.5),
         legend.text = etxt(12), legend.title = etxt(14) )

plotly::ggplotly(gg, tooltip="text") %>% 
  plotly::layout(legend = list(x=0.01, y=0.99, bordercolor="gray"),
                 xaxis = list(fixedrange=TRUE),
                 yaxis = list(fixedrange=TRUE))
```

***

```{r echo =FALSE}
fits %>% map( pluck, "RMSE" ) %>% 
  enframe( "Model", "Root Mean Squared Error" ) %>% unnest() %>%
  knitr::kable("html") %>% kableExtra::column_spec(2, width="1.25in") %>%
  kableExtra::kable_styling(bootstrap_options = "striped",
                            position="center",
                            full_width=FALSE)
```

***

**References:**
[[Data](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data)]
[[Code](https://github.com/ArtemSokolov/covidcurve)]

